import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import BackspaceButton from "@/components/backspace-button";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} bg-gray-800 h-screen max-w-sm m-auto text-white relative`}
      >
        {children}
        <BackspaceButton />
      </body>
    </html>
  );
}
